### ISSUE TITLE
English grammar on the web link

### ISSUE THREAD

**Issue by videophonegeek** [wooorm/double-metaphone#9]
Little thing in your metaphone and double-metaphone demo

"Just write **a** something, and both its phonetics (according to double-metaphone) will show up next to it."

Leave out the "a"

"Just write something, and both its phonetics (according to double-metaphone) will show up next to it."

I have a collection of English oronyms and this algorithm works especially well. Thank you.

**Comment by wooorm** [comment]
Thanks John! All fixed now!

**Comment by videophonegeek** [comment]
Hi Titus,
Very fun and useful code.  I am working on some improved profanity screening offering alternatives which are colorful but not considered profane in English. e.g. "damnit" suggesting "dad gummit" or "dang", and "Jesus Christ" suggesting "Jimminey Cricket".  Also a whole bunch of American English slang is considered offensive. I have a list of about 100 so far.
